Use include "filename" (#4)
Use include "filename" to include programmer-defined header files
from the same directory as the file containing the directive. This
is needed to avoid the following errors when cross-compiling:

ssd1306.c:11:10: fatal error: linux_i2c.h: No such file or directory
main.c:9:10: fatal error: ssd1306.h: No such file or directory

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>